spring:
  application:
    name: webhook_service
  main:
    allow-bean-definition-overriding: true
server:
  port: 9000

graphql:
  servlet:
    exception-handlers-enabled: true
    subscriptions:
      websocket:
        path: /subscriptions
    mapping: /graphql
    enabled: true
    corsEnabled: true

logging:
  level:
    com:
      oembedler:
        moon:
          graphql:
            boot:
              error: debug

keycloak:
  auth-server-url: http://localhost:8081/auth
  realm: flinckr_realm
  resource: flinckr_backend
  public-client: true
  principal-attribute: preferred_username
#  security-constraints[0]:
#    authRoles[0]: admin_user
#    securityCollections[0]:
#      patterns[0]: /graphq/*