spring:
  application:
    name: webhook_service
  main:
    allow-bean-definition-overriding: true
server:
  port: 9000

graphql:
  servlet:
    exception-handlers-enabled: true
    subscriptions:
      websocket:
        path: /subscriptions

logging:
  level:
    com:
      oembedler:
        moon:
          graphql:
            boot:
              error: debug
